package robotgameredux.enums;

public enum RobotStates {
	IDLE, INACTIVE, ACTIVE, MOVING, ATTACKING, DO_NOTHING, TURN_OVER, DESTROY_OBSTACLE, PUSH_OBSTACLE, USE_OBJECT, GIVE_OBJECT, TAKE_WEAPON, TAKE_OBJECT, DESTROYED, RECHARGE;
}
